import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from app.models.entities import Screening, Patient, RiskResult, GaitFeatures

def generate_screening_pdf(
    screening: Screening,
    patient: Patient,
    risk_result: RiskResult,
    gait_features: GaitFeatures | None
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    # Custom Brand Colors
    primary_color = colors.HexColor("#135D9E")
    secondary_color = colors.HexColor("#0B8F87")
    dark_text = colors.HexColor("#17202A")
    warning_bg = colors.HexColor("#FFF8E1")
    warning_border = colors.HexColor("#E7AA18")

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=primary_color
    )

    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=secondary_color
    )

    h2_style = ParagraphStyle(
        'H2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=primary_color,
        spaceBefore=8,
        spaceAfter=4
    )

    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=dark_text
    )

    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#C62828")
    )

    elements = []

    # Header
    elements.append(Paragraph("OSTEOGUARD-NER | Clinical Screening Summary", title_style))
    elements.append(Paragraph("DhruveX - AI-Assisted Osteoarthritis Risk Screening Support", subtitle_style))
    elements.append(Spacer(1, 8))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=primary_color, spaceBefore=2, spaceAfter=8))

    # Mandatory Safety Alert Box
    disclaimer_text = (
        "<b>IMPORTANT MEDICAL DISCLAIMER:</b> This report is generated by an AI-assisted risk screening "
        "and decision-support system. It is <b>NOT</b> a definitive clinical diagnosis of osteoarthritis. "
        "Definitive evaluation requires clinical examination, imaging (X-ray/MRI), or laboratory testing "
        "by a certified clinician."
    )
    disclaimer_table = Table([[Paragraph(disclaimer_text, disclaimer_style)]], colWidths=[540])
    disclaimer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), warning_bg),
        ('BOX', (0, 0), (-1, -1), 1, warning_border),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(disclaimer_table)
    elements.append(Spacer(1, 10))

    # Patient & Screening Meta Table
    patient_info = [
        [
            Paragraph(f"<b>Patient Code:</b> {patient.patient_code}", body_style),
            Paragraph(f"<b>Age / Gender:</b> {patient.age} yrs / {patient.gender}", body_style)
        ],
        [
            Paragraph(f"<b>BMI:</b> {patient.bmi} kg/m² ({patient.height_cm}cm, {patient.weight_kg}kg)", body_style),
            Paragraph(f"<b>Location:</b> {patient.village}, {patient.district}", body_style)
        ],
        [
            Paragraph(f"<b>Screening ID:</b> {str(screening.id)[:8]}...", body_style),
            Paragraph(f"<b>Date (UTC):</b> {screening.started_at.strftime('%Y-%m-%d %H:%M')}", body_style)
        ]
    ]
    pt_table = Table(patient_info, colWidths=[270, 270])
    pt_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F5F9FC")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(Paragraph("Patient Information", h2_style))
    elements.append(pt_table)
    elements.append(Spacer(1, 10))

    # Screening Risk Results Table
    risk_score_str = f"{risk_result.risk_score} / 100" if risk_result.risk_score is not None else "N/A (Incomplete)"
    risk_cat = risk_result.risk_category
    
    risk_bg = colors.HexColor("#E8F5E9") if risk_cat == "LOW" else (
        colors.HexColor("#FFF3E0") if risk_cat == "MODERATE" else colors.HexColor("#FFEBEE")
    )

    risk_info = [
        [
            Paragraph(f"<b>Screening Risk Category:</b> {risk_cat}", body_style),
            Paragraph(f"<b>Risk Score:</b> {risk_score_str}", body_style)
        ],
        [
            Paragraph(f"<b>Confidence:</b> {int(risk_result.confidence * 100)}%", body_style),
            Paragraph(f"<b>Data Completeness:</b> {int(risk_result.data_completeness * 100)}%", body_style)
        ],
        [
            Paragraph(f"<b>Model Version:</b> {risk_result.model_version}", body_style),
            Paragraph(f"<b>Clinical Review Required:</b> {'YES' if risk_result.clinician_review_required else 'NO'}", body_style)
        ]
    ]
    risk_table = Table(risk_info, colWidths=[270, 270])
    risk_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), risk_bg),
        ('BOX', (0, 0), (-1, -1), 1, primary_color),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(Paragraph("AI Screening Risk Assessment", h2_style))
    elements.append(risk_table)
    elements.append(Spacer(1, 10))

    # Gait Biomechanics Summary (if available)
    if gait_features:
        gait_info = [
            [
                Paragraph(f"<b>Cadence:</b> {round(gait_features.cadence, 1)} steps/min", body_style),
                Paragraph(f"<b>Gait Asymmetry:</b> {round(gait_features.gait_asymmetry * 100, 1)}%", body_style)
            ],
            [
                Paragraph(f"<b>Knee ROM:</b> {round(gait_features.estimated_knee_motion, 1)}°", body_style),
                Paragraph(f"<b>Step Variability:</b> {round(gait_features.step_variability, 3)}s", body_style)
            ],
            [
                Paragraph(f"<b>Thigh Range:</b> {round(gait_features.thigh_angular_range, 1)}°", body_style),
                Paragraph(f"<b>Shin Range:</b> {round(gait_features.shin_angular_range, 1)}°", body_style)
            ]
        ]
        gait_table = Table(gait_info, colWidths=[270, 270])
        gait_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.white),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        elements.append(Paragraph("Wearable Sensor Biomechanics (ESP32-S3 Dual IMU)", h2_style))
        elements.append(gait_table)
        elements.append(Spacer(1, 10))

    # Contributing Factors
    if risk_result.contributing_factors:
        elements.append(Paragraph("Factors Contributing to this Screening Estimate", h2_style))
        factor_rows = [[Paragraph("<b>Factor</b>", body_style), Paragraph("<b>Contribution</b>", body_style), Paragraph("<b>Clinical Explanation</b>", body_style)]]
        for f in risk_result.contributing_factors:
            factor_rows.append([
                Paragraph(f.label, body_style),
                Paragraph(f"{int(f.contribution * 100)}%", body_style),
                Paragraph(f.explanation, body_style)
            ])
        factor_table = Table(factor_rows, colWidths=[160, 80, 300])
        factor_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ('PADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(factor_table)
        elements.append(Spacer(1, 10))

    # Guidance & Recommendations
    elements.append(Paragraph("Recommended Next Steps", h2_style))
    elements.append(Paragraph(f"• <b>Action:</b> {risk_result.recommendation}", body_style))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph("• <b>General Guidance:</b> Gentle joint mobilization as tolerated, avoid acute aggravation, consult certified physiotherapist.", body_style))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
